<?php
// Auto-generated from the products database table — see admin.php.
// Manage products via Admin → Products instead of editing this file directly.
$products = [
    [
        'id'       => 1,
        'name'     => 'White Executive Longsleeve',
        'category' => 'Clothes',
        'price'    => 4800,
        'image'    => 'img/shirt2.png',
        'featured' => true,
        'wide'     => true,
        'stock'    => 25,
    ],
    [
        'id'       => 2,
        'name'     => 'Black Executive Longsleeve',
        'category' => 'Clothes',
        'price'    => 4800,
        'image'    => 'img/shirt1.png',
        'featured' => false,
        'wide'     => true,
        'stock'    => 25,
    ],
    [
        'id'       => 3,
        'name'     => 'Dark Blue Executive Longsleeve',
        'category' => 'Clothes',
        'price'    => 4800,
        'image'    => 'img/shirt3.png',
        'featured' => false,
        'wide'     => true,
        'stock'    => 25,
    ],
    [
        'id'       => 4,
        'name'     => 'Biege Executive Longsleeve',
        'category' => 'Clothes',
        'price'    => 4800,
        'image'    => 'img/shirt4.png',
        'featured' => false,
        'wide'     => true,
        'stock'    => 25,
    ],
    [
        'id'       => 5,
        'name'     => 'Raw Hem Denim Trousers',
        'category' => 'Clothes',
        'price'    => 2100,
        'image'    => 'img/baggy1.jpeg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 30,
    ],
    [
        'id'       => 6,
        'name'     => 'Washed Cotton Tee',
        'category' => 'Clothes',
        'price'    => 890,
        'image'    => 'img/cotton1.jpeg',
        'featured' => false,
        'wide'     => false,
        'stock'    => 40,
    ],
    [
        'id'       => 7,
        'name'     => 'Merino Wool Crewneck',
        'category' => 'Clothes',
        'price'    => 3400,
        'image'    => 'img/wool1.jpeg',
        'featured' => false,
        'wide'     => false,
        'stock'    => 20,
    ],
    [
        'id'       => 8,
        'name'     => 'Minimal Leather Bag',
        'category' => 'Accessories',
        'price'    => 3200,
        'image'    => 'img/bag1.jpeg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 15,
    ],
    [
        'id'       => 9,
        'name'     => 'Woven Leather Belt',
        'category' => 'Accessories',
        'price'    => 1100,
        'image'    => 'img/belt1.jpeg',
        'featured' => false,
        'wide'     => false,
        'stock'    => 35,
    ],
    [
        'id'       => 10,
        'name'     => 'Brushed Silver Ring',
        'category' => 'Accessories',
        'price'    => 980,
        'image'    => 'img/ring1.jpeg',
        'featured' => false,
        'wide'     => false,
        'stock'    => 30,
    ],
    [
        'id'       => 11,
        'name'     => 'DCO Wireless Speaker',
        'category' => 'Devices',
        'price'    => 5500,
        'image'    => 'img/speaker1.jpeg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 10,
    ],
    [
        'id'       => 12,
        'name'     => 'Noise-Cancel Earphones',
        'category' => 'Devices',
        'price'    => 4200,
        'image'    => 'img/device1.jpeg',
        'featured' => false,
        'wide'     => false,
        'stock'    => 12,
    ],
    [
        'id'       => 13,
        'name'     => 'Noir Santal Eau de Parfum',
        'category' => 'Fragrance',
        'price'    => 12600,
        'image'    => 'img/perfume1.jpeg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 8,
    ],
    [
        'id'       => 14,
        'name'     => 'Amber & Oud Diffuser Set',
        'category' => 'Fragrance',
        'price'    => 11800,
        'image'    => 'img/perfume2.jpeg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 0,
    ],
    [
        'id'       => 16,
        'name'     => 'Venom Wave (5090)',
        'category' => 'Devices',
        'price'    => 120000,
        'image'    => 'img/venom-wave-5090-1781672757.jpg',
        'featured' => true,
        'wide'     => false,
        'stock'    => 3,
    ],
];
